### ISSUE TITLE
Dockerの設定を見直す

### ISSUE THREAD

**Issue by dommyttdev** [dommyttdev/shopping-demo#10]
![medium](https://img.shields.io/badge/priority-medium-yellow)

The configuration for `merchandise-api-db` and `user-api-db` are almost identical. Consider using YAML anchors and aliases to reduce duplication and improve maintainability. This will make it easier to update configurations consistently across both services.

For example, you could define a common configuration and then extend it for each service.

```
  db_common:
    build: .
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  merchandise-api-db:
    <<: *db_common
    container_name: postgres_merchandise_api
    ports:
      - "5001:5432"
    volumes:
      - merchandise-api-db-store:/var/lib/postgresql/data
```

_Originally posted by @gemini-code-assist[bot] in https://github.com/dommyttdev/shopping-demo/pull/9#discussion_r2022342476_
